#NOME PROJETO E CODIFICAÇÃO DE TEXTO
spring.application.name=atlas-os-backend
spring.messages.encoding=UTF-8
#BANCO DE DADOS
spring.datasource.url=jdbc:postgresql://localhost:5432/BD_atlas_os?currentSchema=atlas_os&charSet=UTF-8
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
#HIBERNATE
spring.jpa.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#SWAGGER
springdoc.api-docs.enabled=true
#springdoc.paths-to-exclude=/error, /api/profile**, /api/profile/**
#springdoc.swagger-ui.tagsSorter=alpha
#springdoc.swagger-ui.operationsSorter=alpha
#springdoc.swagger-ui.docExpansion=none
#springdoc.swagger-ui.disable-swagger-default-url=true
#springdoc.swagger-ui.displayRequestDuration=true
#SECURITY
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
#FLYWAY
spring.flyway.locations=classpath:db/migration,classpath:db/test_data